server:
  port: 2003

spring:
  application:
    name: seate-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/seata_account?rewriteBatchedStatements=true&serverTimezone=GMT

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gdit.cloud.domain
seata:
  tx-service-group: dxs_tx_group