server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
    #单机版
  datasource:
    url: jdbc:mysql://localhost:3306/cloud2022?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
# 单机版
eureka:
  instance:
    hostname: localhost  #eureka服务端的实例名字
  client:
    register-with-eureka: true    #表示不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/,http://${eureka.instance.hostname}:7002/eureka/
mybatis:
  type-aliases-package: entity
  mapper-locations: classpath:mapper/*.xml