server:
  port: 8401
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #??8719??????????????8719????+1??????????????
        port: 8719
        dashboard: localhost:8080
  application:
    name: sentinel-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
